version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
      - run: sudo apt-key del 7fa2af80 && sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub
      - run: apt-get update && apt-get install -y git ssh unzip
      - checkout
      - add_ssh_keys
            
      - run: 
          name: Install z3 
          no_output_timeout: 30m
          command: |
            z3 --version
            wget https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.9.1.tar.gz
            tar -xvzf z3-4.9.1.tar.gz
            mkdir z3-z3-4.9.1/build
            cd z3-z3-4.9.1/build 
            cmake -G "Unix Makefiles" ../
            make -j4
            cp z3 /usr/bin/
            z3 --version
            
      - run:
          name: Test Examples 
          command: stack setup && stack build && stack test
